---
- name: create a conf file for docker
  hosts: webservers
  vars_files:
    - vars/docker-conf-vars.yml
  gather_facts: false

  tasks:
    - name: create directories for data and logs
      include_tasks: tasks/docker-conf.yml
      loop:
        - { dest: 'mytb-data' }
        - { dest: 'mytb-logs' }

    - name: create conf file for docker
      ansible.builtin.template:
        src: templates/docker-compose-config.j2
        dest: docker-compose.yml
