---
- name: install docker and docker-compose
  hosts: webservers
  gather_facts: yes

  tasks:
    - name: update apt and install docker
      ansible.builtin.apt:
        update-cache: true
        name: docker.io
      become: true

    - name: install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.5.1/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 755
      become: true